name: Deploy to AWS ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login a Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build y push de la imagen
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t 455982475279.dkr.ecr.us-east-1.amazonaws.com/abuelito-web:latest \
            --push .

      - name: Forzar nuevo deployment en ECS
        run: |
          aws ecs update-service \
            --cluster abuelito-cluster2 \
            --service abuelito-service \
            --force-new-deployment
